apiVersion: apps/v1
kind: Deployment
metadata:
  name: cifar10-api
  labels:
    app: cifar10-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cifar10-api
  template:
    metadata:
      labels:
        app: cifar10-api
    spec:
      serviceAccountName: cifar10-api-ksa
      containers:
        - name: cifar10-api
          image: europe-central2-docker.pkg.dev/mlops-500119/cifar10-images/cifar10-api:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: cifar10-api-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5